// <auto-generated />
using System;
using Health_Insurance_Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Health_Insurance_Application.Migrations
{
    [DbContext(typeof(HealthInsuranceContext))]
    [Migration("20240803054022_updated-policy")]
    partial class updatedpolicy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Health_Insurance_Application.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Uid = 103
                        });
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Claims", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"), 1L, 1);

                    b.Property<DateTime>("AcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("AmountApproved")
                        .HasColumnType("real");

                    b.Property<float>("AmountClaimed")
                        .HasColumnType("real");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("ClaimReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClaimedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.HasKey("ClaimId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            ClaimId = 1,
                            AcceptedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AmountApproved = 1500f,
                            AmountClaimed = 2000f,
                            ApprovedBy = 1,
                            ClaimReason = "Hosiptal Bills",
                            ClaimStatus = "Approved",
                            ClaimedDate = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(6006),
                            CustomerId = 10001,
                            PolicyId = 1
                        });
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.CorporateEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("CorporateEmployees");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("EmergenceyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 10001,
                            EmergenceyContact = "888888888",
                            Uid = 101
                        });
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AadharId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hosiptals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchCode = "Kmm05",
                            City = "Khammam",
                            Name = "Hosiptal A",
                            State = "Telangana",
                            Street = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            Zipcode = 507001
                        });
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.HospitalAgent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentId"), 1L, 1);

                    b.Property<string>("AgentContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HosiptalId")
                        .HasColumnType("int");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.HasKey("AgentId");

                    b.HasIndex("HosiptalId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("HospitalAgents");

                    b.HasData(
                        new
                        {
                            AgentId = 11111,
                            AgentContact = "7000001111",
                            HosiptalId = 1,
                            Uid = 102
                        });
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<float>("PaymentAmount")
                        .HasColumnType("real");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PaymentDone")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            CustomerId = 10001,
                            PaymentAmount = 500f,
                            PaymentDate = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(6045),
                            PaymentDone = false,
                            PaymentDueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = "Completed",
                            PaymentType = 0,
                            PolicyId = 1,
                            Remarks = "First payment of the year",
                            TransactionId = 100001
                        });
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"), 1L, 1);

                    b.Property<int>("CoverageYears")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextPaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PolicyEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PolicyExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PolicyStartDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("PremiumAmount")
                        .HasColumnType("real");

                    b.Property<float>("QuoteAmount")
                        .HasColumnType("real");

                    b.Property<int>("QuotePaymentTerm")
                        .HasColumnType("int");

                    b.Property<string>("RenewalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SchemeId");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            PolicyId = 1,
                            CoverageYears = 0,
                            CustomerId = 10001,
                            LastPaymentDate = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5925),
                            NextPaymentDueDate = new DateTime(2025, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5925),
                            PaymentFrequency = "Quarterly",
                            PolicyEndDate = new DateTime(2025, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5921),
                            PolicyExpiryDate = new DateTime(2025, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5927),
                            PolicyStartDate = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5921),
                            PremiumAmount = 500f,
                            QuoteAmount = 1000f,
                            QuotePaymentTerm = 0,
                            RenewalStatus = "Renwed",
                            SchemeId = 1
                        });
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Renewal", b =>
                {
                    b.Property<int>("RenewalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RenewalId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<float>("DiscountApplied")
                        .HasColumnType("real");

                    b.Property<DateTime>("NewPolicyStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RenewalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RenewalId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Renewals");

                    b.HasData(
                        new
                        {
                            RenewalId = 1,
                            CustomerId = 10001,
                            DiscountApplied = 0f,
                            NewPolicyStartDate = new DateTime(2025, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(6059),
                            PolicyId = 1,
                            RenewalDate = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(6058),
                            RenewalStatus = "Pending"
                        },
                        new
                        {
                            RenewalId = 2,
                            CustomerId = 10001,
                            DiscountApplied = 100f,
                            NewPolicyStartDate = new DateTime(2026, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(6061),
                            PolicyId = 1,
                            RenewalDate = new DateTime(2025, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(6060),
                            RenewalStatus = "Renwed"
                        });
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Scheme", b =>
                {
                    b.Property<int>("SchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchemeId"), 1L, 1);

                    b.Property<float>("BaseCoverageAmount")
                        .HasColumnType("real");

                    b.Property<float>("BasePremiumAmount")
                        .HasColumnType("real");

                    b.Property<float>("CoverageAmount")
                        .HasColumnType("real");

                    b.Property<int>("CoverageYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentTerm")
                        .HasColumnType("int");

                    b.Property<string>("RouteTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchemeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SchemeLastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SchemeStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchemeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmallDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchemeId");

                    b.ToTable("Schemes");

                    b.HasData(
                        new
                        {
                            SchemeId = 1,
                            BaseCoverageAmount = 100000f,
                            BasePremiumAmount = 5000f,
                            CoverageAmount = 500000f,
                            CoverageYears = 10,
                            IsActive = true,
                            PaymentTerm = 5,
                            RouteTitle = "individual-basic-plan",
                            SchemeDescription = "The Individual Basic Plan offers essential health coverage for individuals at an affordable premium. This plan includes coverage for hospitalization, surgery, and emergency care. It is designed for those seeking fundamental protection against medical expenses.",
                            SchemeLastUpdatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5940),
                            SchemeName = "Individual Basic Plan",
                            SchemeStartedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchemeType = "Individual",
                            SmallDescription = "A Plan For Every Individual Which Covers Basic Need"
                        },
                        new
                        {
                            SchemeId = 2,
                            BaseCoverageAmount = 250000f,
                            BasePremiumAmount = 10000f,
                            CoverageAmount = 1000000f,
                            CoverageYears = 15,
                            IsActive = true,
                            PaymentTerm = 7,
                            RouteTitle = "individual-premium-plan",
                            SchemeDescription = "The Individual Premium Plan provides extensive health coverage for individuals, including benefits for outpatient treatments, specialist consultations, and preventive care. This plan is ideal for those who want a higher level of health security and comprehensive medical benefits.",
                            SchemeLastUpdatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5942),
                            SchemeName = "Individual Premium Plan",
                            SchemeStartedAt = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchemeType = "Individual",
                            SmallDescription = "A Plan For Every Person Which Covers the Needs"
                        },
                        new
                        {
                            SchemeId = 3,
                            BaseCoverageAmount = 500000f,
                            BasePremiumAmount = 20000f,
                            CoverageAmount = 2000000f,
                            CoverageYears = 20,
                            IsActive = true,
                            PaymentTerm = 10,
                            RouteTitle = "individual-elite-plan",
                            SchemeDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem totam similique nobis dolore in, velit consectetur perspiciatis vero quas. Esse deleniti commodi perferendis officia saepe natus, quas dolor. Perspiciatis iusto nam optio quo natus amet velit explicabo quod, officia adipisci quia ipsum odio deleniti, fugiat esse illum tenetur obcaecati corporis quasi quibusdam dolorum laboriosam in. Numquam autem temporibus molestiae delectus sequi cupiditate suscipit natus facere enim dolorum sed eaque voluptas repellendus officiis et doloremque totam pariatur, quae, non amet explicabo. Maxime, magni! Ea voluptate aspernatur impedit vitae quasi necessitatibus. Ex, commodi quaerat. Dolor deleniti eos amet non. Optio minima quos incidunt recusandae eveniet, consequuntur earum quam nesciunt tenetur deserunt voluptas tempora ipsa omnis ipsam a iusto rerum, obcaecati aut nulla quo, blanditiis perferendis? Quam quo alias error possimus impedit sapiente commodi earum quaerat? Quas natus rem voluptate, at nostrum ut itaque voluptatibus porro velit labore consequatur obcaecati et nulla nihil cum, provident ratione iusto esse iure! Porro, totam cumque molestias officia minus vel molestiae, quod alias excepturi pariatur voluptates quae, cupiditate voluptatem fugit delectus. Ipsa temporibus similique odit veniam quo, cupiditate nesciunt dignissimos consequuntur aperiam, eveniet facilis recusandae voluptates nulla quaerat mollitia labore quae! Sapiente odio deserunt eum suscipit.",
                            SchemeLastUpdatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5944),
                            SchemeName = "Individual Elite Plan",
                            SchemeStartedAt = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchemeType = "Individual",
                            SmallDescription = "A Plan for Every Individual for every need"
                        },
                        new
                        {
                            SchemeId = 4,
                            BaseCoverageAmount = 200000f,
                            BasePremiumAmount = 15000f,
                            CoverageAmount = 1000000f,
                            CoverageYears = 10,
                            IsActive = true,
                            PaymentTerm = 5,
                            RouteTitle = "corporate-standard-plan",
                            SchemeDescription = "The Corporate Standard Plan offers essential health coverage for employees of small and medium-sized businesses. It includes hospitalization and emergency care benefits, providing basic protection to ensure the well-being of your workforce.",
                            SchemeLastUpdatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5947),
                            SchemeName = "Corporate Standard Plan",
                            SchemeStartedAt = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchemeType = "Corporate",
                            SmallDescription = "A Plan For Every Corporate Standard Covers basic need"
                        },
                        new
                        {
                            SchemeId = 5,
                            BaseCoverageAmount = 500000f,
                            BasePremiumAmount = 30000f,
                            CoverageAmount = 2500000f,
                            CoverageYears = 15,
                            IsActive = true,
                            PaymentTerm = 7,
                            RouteTitle = "corporate-comprehensive-plan",
                            SchemeDescription = "The Corporate Comprehensive Plan provides extensive health coverage for employees, including benefits for outpatient treatments, preventive care, and specialist consultations. This plan is designed for businesses that want to offer their employees a higher level of health security and comprehensive medical benefits.",
                            SchemeLastUpdatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5948),
                            SchemeName = "Corporate Comprehensive Plan",
                            SchemeStartedAt = new DateTime(2020, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchemeType = "Corporate",
                            SmallDescription = "A Huge Amount Coverage For  Corporate with Higer number Of Employeess "
                        },
                        new
                        {
                            SchemeId = 6,
                            BaseCoverageAmount = 1000000f,
                            BasePremiumAmount = 50000f,
                            CoverageAmount = 5000000f,
                            CoverageYears = 20,
                            IsActive = true,
                            PaymentTerm = 10,
                            RouteTitle = "corporate-premium-plan",
                            SchemeDescription = "The Corporate Premium Plan offers the highest level of health coverage for corporate employees, including extensive inpatient and outpatient benefits, dental care, and access to a wide network of top healthcare providers. This plan is tailored for businesses that seek to provide the ultimate health protection and peace of mind for their employees.",
                            SchemeLastUpdatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5949),
                            SchemeName = "Corporate Premium Plan",
                            SchemeStartedAt = new DateTime(2021, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchemeType = "Corporate",
                            SmallDescription = "Best Corporate Plan , with Highest Claim Sucess Rate"
                        },
                        new
                        {
                            SchemeId = 7,
                            BaseCoverageAmount = 200000f,
                            BasePremiumAmount = 20000f,
                            CoverageAmount = 1000000f,
                            CoverageYears = 10,
                            IsActive = true,
                            PaymentTerm = 5,
                            RouteTitle = "family-basic-plan",
                            SchemeDescription = "The Family Basic Plan offers essential health coverage for families, including hospitalization and emergency care benefits. This plan is designed to provide fundamental protection for your family’s health needs at an affordable premium.",
                            SchemeLastUpdatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5950),
                            SchemeName = "Family Basic Plan",
                            SchemeStartedAt = new DateTime(2018, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchemeType = "Family",
                            SmallDescription = "The best plan with lowest Rate"
                        },
                        new
                        {
                            SchemeId = 8,
                            BaseCoverageAmount = 600000f,
                            BasePremiumAmount = 40000f,
                            CoverageAmount = 3000000f,
                            CoverageYears = 15,
                            IsActive = true,
                            PaymentTerm = 7,
                            RouteTitle = "family-comprehensive-plan",
                            SchemeDescription = "The Family Comprehensive Plan provides extensive health coverage for families, including benefits for outpatient treatments, specialist consultations, and preventive care. This plan is ideal for families seeking a higher level of health security and comprehensive medical benefits.",
                            SchemeLastUpdatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5951),
                            SchemeName = "Family Comprehensive Plan",
                            SchemeStartedAt = new DateTime(2019, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchemeType = "Family",
                            SmallDescription = "Huge Amount Coverage which solves most of the needs"
                        },
                        new
                        {
                            SchemeId = 9,
                            BaseCoverageAmount = 1200000f,
                            BasePremiumAmount = 60000f,
                            CoverageAmount = 6000000f,
                            CoverageYears = 20,
                            IsActive = true,
                            PaymentTerm = 10,
                            RouteTitle = "family-elite-plan",
                            SchemeDescription = "The Family Elite Plan offers the highest level of health coverage for families, including extensive inpatient and outpatient benefits, dental care, and access to a wide network of top healthcare providers. This plan is tailored for families that seek the ultimate health protection and peace of mind.",
                            SchemeLastUpdatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5952),
                            SchemeName = "Family Elite Plan",
                            SchemeStartedAt = new DateTime(2020, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchemeType = "Family",
                            SmallDescription = "The best Plan To Take Care of your family from every danger"
                        });
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.User", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Uid = 101,
                            Address = "St Street opp lalbagh, chennai , TamilNadu",
                            CreatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5725),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer1@gmail.com",
                            FirstName = "Customer",
                            Gender = "Male",
                            LastName = "Test",
                            LastUpdated = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5741),
                            MobileNumber = "9999999991",
                            Password = new byte[] { 234, 234, 174, 201, 190, 120, 206, 209, 81, 129, 185, 174, 40, 20, 167, 97, 8, 183, 72, 236, 253, 155, 77, 30, 241, 206, 187, 87, 101, 116, 76, 42, 71, 194, 166, 137, 184, 44, 249, 212, 250, 133, 2, 225, 161, 164, 202, 247, 213, 11, 250, 187, 168, 167, 25, 1, 25, 109, 241, 12, 144, 139, 177, 204 },
                            Role = "Customer",
                            Salt = new byte[] { 185, 142, 169, 216, 226, 11, 84, 0, 49, 227, 142, 246, 51, 17, 40, 205, 66, 41, 59, 172, 116, 43, 188, 223, 57, 174, 124, 144, 84, 82, 145, 85, 99, 18, 194, 137, 55, 245, 57, 46, 114, 177, 130, 7, 178, 105, 68, 137, 135, 218, 211, 2, 178, 83, 30, 227, 254, 11, 191, 238, 132, 41, 105, 26, 86, 60, 237, 90, 172, 196, 11, 82, 75, 171, 225, 190, 143, 210, 168, 62, 103, 177, 37, 73, 128, 185, 167, 52, 45, 98, 179, 25, 84, 79, 124, 50, 246, 21, 165, 84, 146, 161, 38, 123, 55, 210, 121, 160, 124, 40, 78, 207, 176, 123, 66, 175, 29, 80, 80, 86, 200, 26, 251, 33, 63, 24, 64, 120 },
                            Zipcode = "507001"
                        },
                        new
                        {
                            Uid = 102,
                            Address = "St Street opp lalbagh, chennai , TamilNadu",
                            CreatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5754),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "agent@gmail.com",
                            FirstName = "Agent",
                            Gender = "Male",
                            LastName = "Test",
                            LastUpdated = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5755),
                            MobileNumber = "9999999999",
                            Password = new byte[] { 234, 234, 174, 201, 190, 120, 206, 209, 81, 129, 185, 174, 40, 20, 167, 97, 8, 183, 72, 236, 253, 155, 77, 30, 241, 206, 187, 87, 101, 116, 76, 42, 71, 194, 166, 137, 184, 44, 249, 212, 250, 133, 2, 225, 161, 164, 202, 247, 213, 11, 250, 187, 168, 167, 25, 1, 25, 109, 241, 12, 144, 139, 177, 204 },
                            Role = "Agent",
                            Salt = new byte[] { 185, 142, 169, 216, 226, 11, 84, 0, 49, 227, 142, 246, 51, 17, 40, 205, 66, 41, 59, 172, 116, 43, 188, 223, 57, 174, 124, 144, 84, 82, 145, 85, 99, 18, 194, 137, 55, 245, 57, 46, 114, 177, 130, 7, 178, 105, 68, 137, 135, 218, 211, 2, 178, 83, 30, 227, 254, 11, 191, 238, 132, 41, 105, 26, 86, 60, 237, 90, 172, 196, 11, 82, 75, 171, 225, 190, 143, 210, 168, 62, 103, 177, 37, 73, 128, 185, 167, 52, 45, 98, 179, 25, 84, 79, 124, 50, 246, 21, 165, 84, 146, 161, 38, 123, 55, 210, 121, 160, 124, 40, 78, 207, 176, 123, 66, 175, 29, 80, 80, 86, 200, 26, 251, 33, 63, 24, 64, 120 },
                            Zipcode = "507002"
                        },
                        new
                        {
                            Uid = 103,
                            Address = "St Street opp lalbagh, chennai , TamilNadu",
                            CreatedAt = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5765),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            Gender = "Male",
                            LastName = "Test",
                            LastUpdated = new DateTime(2024, 8, 3, 11, 10, 21, 566, DateTimeKind.Local).AddTicks(5765),
                            MobileNumber = "111111111",
                            Password = new byte[] { 234, 234, 174, 201, 190, 120, 206, 209, 81, 129, 185, 174, 40, 20, 167, 97, 8, 183, 72, 236, 253, 155, 77, 30, 241, 206, 187, 87, 101, 116, 76, 42, 71, 194, 166, 137, 184, 44, 249, 212, 250, 133, 2, 225, 161, 164, 202, 247, 213, 11, 250, 187, 168, 167, 25, 1, 25, 109, 241, 12, 144, 139, 177, 204 },
                            Role = "Admin",
                            Salt = new byte[] { 185, 142, 169, 216, 226, 11, 84, 0, 49, 227, 142, 246, 51, 17, 40, 205, 66, 41, 59, 172, 116, 43, 188, 223, 57, 174, 124, 144, 84, 82, 145, 85, 99, 18, 194, 137, 55, 245, 57, 46, 114, 177, 130, 7, 178, 105, 68, 137, 135, 218, 211, 2, 178, 83, 30, 227, 254, 11, 191, 238, 132, 41, 105, 26, 86, 60, 237, 90, 172, 196, 11, 82, 75, 171, 225, 190, 143, 210, 168, 62, 103, 177, 37, 73, 128, 185, 167, 52, 45, 98, 179, 25, 84, 79, 124, 50, 246, 21, 165, 84, 146, 161, 38, 123, 55, 210, 121, 160, 124, 40, 78, 207, 176, 123, 66, 175, 29, 80, 80, 86, 200, 26, 251, 33, 63, 24, 64, 120 },
                            Zipcode = "507003"
                        });
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Admin", b =>
                {
                    b.HasOne("Health_Insurance_Application.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Health_Insurance_Application.Models.Admin", "Uid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Claims", b =>
                {
                    b.HasOne("Health_Insurance_Application.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("Health_Insurance_Application.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Health_Insurance_Application.Models.Policy", "Policy")
                        .WithMany("Claims")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.CorporateEmployee", b =>
                {
                    b.HasOne("Health_Insurance_Application.Models.Policy", "Policy")
                        .WithMany("CorporateEmployees")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Customer", b =>
                {
                    b.HasOne("Health_Insurance_Application.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Health_Insurance_Application.Models.Customer", "Uid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.FamilyMember", b =>
                {
                    b.HasOne("Health_Insurance_Application.Models.Policy", "Policy")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.HospitalAgent", b =>
                {
                    b.HasOne("Health_Insurance_Application.Models.Hospital", "Hosiptal")
                        .WithMany("Agents")
                        .HasForeignKey("HosiptalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Health_Insurance_Application.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Health_Insurance_Application.Models.HospitalAgent", "Uid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hosiptal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Payment", b =>
                {
                    b.HasOne("Health_Insurance_Application.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Health_Insurance_Application.Models.Policy", "Policy")
                        .WithMany("Payments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Policy", b =>
                {
                    b.HasOne("Health_Insurance_Application.Models.Customer", "Customer")
                        .WithMany("Policies")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Health_Insurance_Application.Models.Scheme", "Scheme")
                        .WithMany("Policies")
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Scheme");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Renewal", b =>
                {
                    b.HasOne("Health_Insurance_Application.Models.Customer", "Customer")
                        .WithMany("Renewals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Health_Insurance_Application.Models.Policy", "Policy")
                        .WithMany("Renewals")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Customer", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Policies");

                    b.Navigation("Renewals");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Hospital", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Policy", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("CorporateEmployees");

                    b.Navigation("FamilyMembers");

                    b.Navigation("Payments");

                    b.Navigation("Renewals");
                });

            modelBuilder.Entity("Health_Insurance_Application.Models.Scheme", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
